events {}

http {

  resolver 127.0.0.11;

  upstream ingestion_cluster {
      zone ingestion_cluster 64k;
      server ingestion-service:4100 resolve;
  }

  server {
      listen 80;

      location / {
          proxy_pass http://ingestion_cluster;
      }
  }

}